name: GuiKits
main: me.RaidzDev.Main
author: RaizdDev
version: 3.0
commands:
  arena:
  say:
  bc:
  tag:
  tags:
  fly:
  youtuber:
  kits:
  ping:
  loja:
  admin:
  skit:
  setknock:
  knock:
  coins:
  report:
  aplicar:
  lclasses:
  caixa:
  sc:
  chat:
  ffeast:
  setspawn:
  setrdm:
  nofall:
  setfps:
  setmdr:
  kits2:
  setchallenge:
  att:
  atualizacao:
  fps:
  rdm:
  challenge:
  mdr:
  spawn:
  warp:
  gm:
  setarena:
  kit:
  morrer:
  kill:
  suicide: